// Copyright 2025 Redpanda Data, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package generator

import (
	"fmt"
	"go/token"
	"log"
	"path"
	"path/filepath"
	"text/template"

	"github.com/redpanda-data/protoc-gen-go-mcp/pkg/gen"
	"github.com/redpanda-data/protoc-gen-go-mcp/pkg/runtime"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/types/pluginpb"
)

const (
	GeneratedFilenameExtension = ".pb.mcp.go"
)

type FileGenerator struct {
	f   *protogen.File
	gen *protogen.Plugin

	gf           *protogen.GeneratedFile
	openAICompat bool
	debug        bool
}

func NewFileGenerator(f *protogen.File, gen *protogen.Plugin, debug bool) *FileGenerator {
	gen.SupportedFeatures |= uint64(pluginpb.CodeGeneratorResponse_FEATURE_PROTO3_OPTIONAL)

	return &FileGenerator{f: f, gen: gen, debug: debug}
}

func (g *FileGenerator) logf(format string, args ...any) {
	if g.debug {
		log.Printf("[protoc-gen-go-mcp] "+format, args...)
	}
}

// Small templates to generate incrementally, reducing memory pressure

const fileHeaderTemplate = `// Code generated by protoc-gen-mcp-go. DO NOT EDIT.
// source: {{ .SourcePath }}

package {{ .GoPackage }}

import (
  "context"
  "encoding/json"
  "google.golang.org/protobuf/encoding/protojson"
  "connectrpc.com/connect"
  grpc "google.golang.org/grpc"
  "github.com/redpanda-data/protoc-gen-go-mcp/pkg/runtime"
)

var (
`

const toolTemplate = `  {{.Key}}Tool = runtime.Tool{
    Name: {{ printf "%q" .Tool.Name }},
    Description: {{ printf "%q" .Tool.Description }},
    RawInputSchema: json.RawMessage({{ quoteBytes .Tool.RawInputSchema }}),
    RawOutputSchema: json.RawMessage({{ quoteBytes .Tool.RawOutputSchema }}),
  }
`

const varCloseTemplate = `)

`

const handlerTemplate = `
{{- range $serviceName, $methods := .Services }}
// {{$serviceName}}Server is compatible with the grpc-go server interface.
type {{$serviceName}}Server interface {
  {{- range $methodName, $tool := $methods }}
  {{$methodName}}(ctx context.Context, req *{{$tool.RequestType}}) (*{{$tool.ResponseType}}, error)
  {{- end }}
}
{{ end }}

{{- range $key, $val := .Services }}
// Register{{$key}}Handler registers standard MCP handlers for {{$key}}
func Register{{$key}}Handler(s runtime.MCPServer, srv {{$key}}Server, opts ...runtime.Option) {
  config := runtime.NewConfig()
  for _, opt := range opts {
    opt(config)
  }

  {{- range $tool_name, $tool_val := $val }}
  {{$tool_name}}Tool := {{$key}}_{{$tool_name}}Tool
  {{$tool_name}}Tool = runtime.ApplyConfig({{$tool_name}}Tool, config)

  s.AddTool({{$tool_name}}Tool, func(ctx context.Context, request *runtime.CallToolRequest) (*runtime.CallToolResult, error) {
    var req {{$tool_val.RequestType}}

    message := request.Arguments

    // Extract extra properties if configured
    for _, prop := range config.ExtraProperties {
      if propVal, ok := message[prop.Name]; ok {
        ctx = context.WithValue(ctx, prop.ContextKey, propVal)
      }
    }

    marshaled, err := json.Marshal(message)
    if err != nil {
      return nil, err
    }

    if err := (protojson.UnmarshalOptions{DiscardUnknown: true}).Unmarshal(marshaled, &req); err != nil {
      return nil, err
    }

    resp, err := srv.{{$tool_name}}(ctx, &req)
    if err != nil {
      return runtime.HandleError(err)
    }

    marshaled, err = (protojson.MarshalOptions{UseProtoNames: true, EmitDefaultValues: true}).Marshal(resp)
    if err != nil {
      return nil, err
    }

    return runtime.NewToolResultJSON(marshaled), nil
  })
  {{- end }}
}

// Register{{$key}}HandlerOpenAI registers OpenAI-compatible MCP handlers for {{$key}}
func Register{{$key}}HandlerOpenAI(s runtime.MCPServer, srv {{$key}}Server, opts ...runtime.Option) {
  config := runtime.NewConfig()
  for _, opt := range opts {
    opt(config)
  }

  {{- range $tool_name, $tool_val := $val }}
  {{$tool_name}}ToolOpenAI := {{$key}}_{{$tool_name}}ToolOpenAI
  {{$tool_name}}ToolOpenAI = runtime.ApplyConfig({{$tool_name}}ToolOpenAI, config)

  s.AddTool({{$tool_name}}ToolOpenAI, func(ctx context.Context, request *runtime.CallToolRequest) (*runtime.CallToolResult, error) {
    var req {{$tool_val.RequestType}}

    message := request.Arguments

    // Extract extra properties if configured
    for _, prop := range config.ExtraProperties {
      if propVal, ok := message[prop.Name]; ok {
        ctx = context.WithValue(ctx, prop.ContextKey, propVal)
      }
    }

    runtime.FixOpenAI(req.ProtoReflect().Descriptor(), message)

    marshaled, err := json.Marshal(message)
    if err != nil {
      return nil, err
    }

    if err := (protojson.UnmarshalOptions{DiscardUnknown: true}).Unmarshal(marshaled, &req); err != nil {
      return nil, err
    }

    resp, err := srv.{{$tool_name}}(ctx, &req)
    if err != nil {
      return runtime.HandleError(err)
    }

    marshaled, err = (protojson.MarshalOptions{UseProtoNames: true, EmitDefaultValues: true}).Marshal(resp)
    if err != nil {
      return nil, err
    }

    return runtime.NewToolResultJSON(marshaled), nil
  })
  {{- end }}
}

// Register{{$key}}HandlerWithProvider registers handlers for the specified LLM provider
func Register{{$key}}HandlerWithProvider(s runtime.MCPServer, srv {{$key}}Server, provider runtime.LLMProvider, opts ...runtime.Option) {
  switch provider {
  case runtime.LLMProviderOpenAI:
    Register{{$key}}HandlerOpenAI(s, srv, opts...)
  case runtime.LLMProviderStandard:
    fallthrough
  default:
    Register{{$key}}Handler(s, srv, opts...)
  }
}
{{- end }}

{{- range $serviceName, $methods := .Services }}
// {{$serviceName}}Client is compatible with the grpc-go client interface.
type {{$serviceName}}Client interface {
  {{- range $methodName, $tool := $methods }}
  {{$methodName}}(ctx context.Context, req *{{$tool.RequestType}}, opts ...grpc.CallOption) (*{{$tool.ResponseType}}, error)
  {{- end }}
}
{{ end }}


{{- range $serviceName, $methods := .Services }}
// Connect{{$serviceName}}Client is compatible with the connectrpc-go client interface.
type Connect{{$serviceName}}Client interface {
  {{- range $methodName, $tool := $methods }}
  {{$methodName}}(ctx context.Context, req *connect.Request[{{$tool.RequestType}}]) (*connect.Response[{{$tool.ResponseType}}], error)
  {{- end }}
}
{{ end }}

{{- range $key, $val := .Services }}
// ForwardToConnect{{$key}}Client registers a connectrpc client, to forward MCP calls to it.
func ForwardToConnect{{$key}}Client(s runtime.MCPServer, client Connect{{$key}}Client, opts ...runtime.Option) {
  config := runtime.NewConfig()
  for _, opt := range opts {
    opt(config)
  }

  {{- range $tool_name, $tool_val := $val }}
  {{$tool_name}}Tool := {{$key}}_{{$tool_name}}Tool
  {{$tool_name}}Tool = runtime.ApplyConfig({{$tool_name}}Tool, config)

  s.AddTool({{$tool_name}}Tool, func(ctx context.Context, request *runtime.CallToolRequest) (*runtime.CallToolResult, error) {
    var req {{$tool_val.RequestType}}

    message := request.Arguments

    // Extract extra properties if configured
    for _, prop := range config.ExtraProperties {
      if propVal, ok := message[prop.Name]; ok {
        ctx = context.WithValue(ctx, prop.ContextKey, propVal)
      }
    }

    marshaled, err := json.Marshal(message)
    if err != nil {
      return nil, err
    }

    if err := (protojson.UnmarshalOptions{DiscardUnknown: true}).Unmarshal(marshaled, &req); err != nil {
      return nil, err
    }

    resp, err := client.{{$tool_name}}(ctx, connect.NewRequest(&req))
    if err != nil {
      return runtime.HandleError(err)
    }

    marshaled, err = (protojson.MarshalOptions{UseProtoNames: true, EmitDefaultValues: true}).Marshal(resp.Msg)
    if err != nil {
      return nil, err
    }
    return runtime.NewToolResultJSON(marshaled), nil
  })
  {{- end }}
}
{{- end }}

{{- range $key, $val := .Services }}
// ForwardTo{{$key}}Client registers a gRPC client, to forward MCP calls to it.
func ForwardTo{{$key}}Client(s runtime.MCPServer, client {{$key}}Client, opts ...runtime.Option) {
  config := runtime.NewConfig()
  for _, opt := range opts {
    opt(config)
  }

  {{- range $tool_name, $tool_val := $val }}
  {{$tool_name}}Tool := {{$key}}_{{$tool_name}}Tool
  {{$tool_name}}Tool = runtime.ApplyConfig({{$tool_name}}Tool, config)

  s.AddTool({{$tool_name}}Tool, func(ctx context.Context, request *runtime.CallToolRequest) (*runtime.CallToolResult, error) {
    var req {{$tool_val.RequestType}}

    message := request.Arguments

    // Extract extra properties if configured
    for _, prop := range config.ExtraProperties {
      if propVal, ok := message[prop.Name]; ok {
        ctx = context.WithValue(ctx, prop.ContextKey, propVal)
      }
    }

    marshaled, err := json.Marshal(message)
    if err != nil {
      return nil, err
    }

    if err := (protojson.UnmarshalOptions{DiscardUnknown: true}).Unmarshal(marshaled, &req); err != nil {
      return nil, err
    }

    resp, err := client.{{$tool_name}}(ctx, &req)
    if err != nil {
      return runtime.HandleError(err)
    }

    marshaled, err = (protojson.MarshalOptions{UseProtoNames: true, EmitDefaultValues: true}).Marshal(resp)
    if err != nil {
      return nil, err
    }
    return runtime.NewToolResultJSON(marshaled), nil
  })
  {{- end }}
}
{{- end }}


`

type TplParams struct {
	PackageName string
	SourcePath  string
	GoPackage   string
	Tools       map[string]runtime.Tool
	ToolsOpenAI map[string]runtime.Tool
	Services    map[string]map[string]Tool
}

type Tool struct {
	RequestType   string
	ResponseType  string
	MCPTool       runtime.Tool
	MCPToolOpenAI runtime.Tool
}

// LazyTool holds method descriptors instead of pre-generated schemas
// to reduce memory consumption during generation
type LazyTool struct {
	RequestType  string
	ResponseType string
	Method       protoreflect.MethodDescriptor
	Comment      string
}

// Delegate to gen package - kept for backward compatibility with tests in this package.
var (
	kindToType          = gen.KindToType
	cleanComment        = gen.CleanComment
	MangleHeadIfTooLong = gen.MangleHeadIfTooLong
	Base36String        = gen.Base36String
)

// messageSchema delegates to the gen package.
func (g *FileGenerator) messageSchema(md protoreflect.MessageDescriptor) map[string]any {
	return gen.MessageSchema(md, gen.SchemaOptions{OpenAICompat: g.openAICompat})
}

// getType delegates to the gen package.
func (g *FileGenerator) getType(fd protoreflect.FieldDescriptor) map[string]any {
	return gen.FieldSchema(fd, gen.SchemaOptions{OpenAICompat: g.openAICompat})
}

func (g *FileGenerator) Generate(packageSuffix string) {
	file := g.f
	if len(g.f.Services) == 0 {
		return
	}
	g.logf("Starting generation for file: %s", file.Desc.Path())

	goImportPath := file.GoImportPath
	if packageSuffix != "" {
		if !token.IsIdentifier(packageSuffix) {
			g.gen.Error(fmt.Errorf("package_suffix %q is not a valid Go identifier", packageSuffix))
			return
		}
		file.GoPackageName += protogen.GoPackageName(packageSuffix)
		generatedFilenamePrefixToSlash := filepath.ToSlash(file.GeneratedFilenamePrefix)
		file.GeneratedFilenamePrefix = path.Join(
			path.Dir(generatedFilenamePrefixToSlash),
			string(file.GoPackageName),
			path.Base(generatedFilenamePrefixToSlash),
		)
		goImportPath = protogen.GoImportPath(path.Join(
			string(file.GoImportPath),
			string(file.GoPackageName),
		))
	}

	g.gf = g.gen.NewGeneratedFile(
		file.GeneratedFilenamePrefix+GeneratedFilenameExtension,
		goImportPath,
	)
	if packageSuffix != "" {
		g.gf.Import(file.GoImportPath)
	}

	// Parse small templates once
	toolTpl, err := template.New("tool").Funcs(template.FuncMap{
		"quoteBytes": func(b []byte) string {
			return fmt.Sprintf("%q", string(b))
		},
	}).Parse(toolTemplate)
	if err != nil {
		g.gen.Error(err)
		return
	}

	handlerTpl, err := template.New("handler").Funcs(template.FuncMap{}).Parse(handlerTemplate)
	if err != nil {
		g.gen.Error(err)
		return
	}

	// Write file header
	g.gf.P("// Code generated by protoc-gen-mcp-go. DO NOT EDIT.")
	g.gf.P("// source: ", g.f.Desc.Path())
	g.gf.P()
	g.gf.P("package ", g.f.GoPackageName)
	g.gf.P()
	g.gf.P("import (")
	g.gf.P("  \"context\"")
	g.gf.P("  \"encoding/json\"")
	g.gf.P("  \"google.golang.org/protobuf/encoding/protojson\"")
	g.gf.P("  \"connectrpc.com/connect\"")
	g.gf.P("  grpc \"google.golang.org/grpc\"")
	g.gf.P("  \"github.com/redpanda-data/protoc-gen-go-mcp/pkg/runtime\"")
	g.gf.P(")")
	g.gf.P()
	g.gf.P()
	g.gf.P("var (")

	// Stream tool definitions - generate and write one at a time to reduce memory
	services := map[string]map[string]Tool{}

	for _, svc := range g.f.Services {
		g.logf("  Processing service: %s", svc.Desc.FullName())
		s := map[string]Tool{}

		for _, meth := range svc.Methods {
			if meth.Desc.IsStreamingClient() || meth.Desc.IsStreamingServer() {
				continue
			}
			g.logf("    Processing method: %s", meth.Desc.FullName())

			comment := string(meth.Comments.Leading)

			// Generate ONE tool at a time, write it, then let it be GC'd
			toolStandard, toolOpenAI := gen.ToolForMethod(meth.Desc, comment)
			toolKey := svc.GoName + "_" + meth.GoName

			// Execute tool template for standard variant
			if err := toolTpl.Execute(g.gf, map[string]any{
				"Key":  toolKey,
				"Tool": toolStandard,
			}); err != nil {
				g.gen.Error(err)
				return
			}

			// Execute tool template for OpenAI variant
			if err := toolTpl.Execute(g.gf, map[string]any{
				"Key":  toolKey + "OpenAI",
				"Tool": toolOpenAI,
			}); err != nil {
				g.gen.Error(err)
				return
			}

			// Store lightweight metadata (no schemas) for handler generation
			s[meth.GoName] = Tool{
				RequestType:   g.gf.QualifiedGoIdent(meth.Input.GoIdent),
				ResponseType:  g.gf.QualifiedGoIdent(meth.Output.GoIdent),
				MCPTool:       runtime.Tool{Name: toolStandard.Name},
				MCPToolOpenAI: runtime.Tool{Name: toolOpenAI.Name},
			}

			// toolStandard and toolOpenAI are now out of scope and can be GC'd
		}
		services[string(svc.Desc.Name())] = s
	}

	g.gf.P(")")
	g.gf.P()

	// Generate handler functions using template (lightweight - no schemas)
	params := TplParams{
		PackageName: string(g.f.Desc.Package()),
		SourcePath:  g.f.Desc.Path(),
		GoPackage:   string(g.f.GoPackageName),
		Services:    services,
		Tools:       nil, // Not needed - already written
		ToolsOpenAI: nil, // Not needed - already written
	}

	if err := handlerTpl.Execute(g.gf, params); err != nil {
		g.gen.Error(err)
		return
	}

	g.logf("Finished generation for file: %s", file.Desc.Path())
}
